baseURL = "https://nav.bahuangshanren.tech/"
languageCode = "zh-CN"
title = "八荒山人导航"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
[params]
  author = "BahuangShanren"
  description = "A navigation website for my own use"
